<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\TriDict.Domain.Shared\TriDict.Domain.Shared.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Volo.Abp.Authorization" />
    <PackageReference Include="Volo.Abp.Ddd.Application.Contracts" />
  </ItemGroup>

</Project>
